config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: 'register', controllers: { sessions: "users/sessions" } do
    
  end
  
  resources :products
  resources :orders
  resources :line_items
  resources :carts
  
  resources :users, shallow: true do
    resource :profile
    resources :orders
  end

  root                    'static_pages#home'
  get 'about',        to: 'static_pages#about'
  get 'contact',      to: 'static_pages#contact'
  get 'store/index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :firstname, :lastname, :prescription_num, :phonenum, :address1, :city, :zipcode, :prescription_card, :idcard
  ######################################################
  # Paperclip Image Attachment
  
  has_attached_file :prescription_card,
    styles: { normal: "200x200#", bigger: "700x700#" },
    default_style: :normal,
    preserve_files: true

  validates_attachment_content_type :prescription_card, content_type: /^image\/(jpeg|png|gif|tiff|jpg)$/
  
  has_attached_file :idcard,
    styles: { normal: "200x200#", bigger: "700x700#" },
    default_style: :normal,
    preserve_files: true

  validates_attachment_content_type :idcard, content_type: /^image\/(jpeg|png|gif|tiff|jpg)$/
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for current_user, html: { class: "form-horizontal col-sm-12"}, multipart: true, remote: true, authenticity_token: true do |f| %>
  <%= f.fields_for :profile do |m| %>
	<% if current_user.profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= m.label "First Name", class: "col-sm-2 col-xs-12" %>
    <%= m.text_field :firstname, class: "col-sm-10 col-xs-12" %>
  </div>
  
  <div class="form-group">
    <%= m.label "Last Name", class: "col-sm-2 col-xs-12" %>
    <%= m.text_field :lastname, class: "col-sm-10 col-xs-12" %>
  </div>
  
  <div class="form-group">
    <%= m.label "Phone #", class: "col-sm-2 col-xs-12" %>
    <%= m.text_field :phonenum, class: "col-sm-10 col-xs-12" %>
  </div>
  
  <div class="form-group">
    <%= m.label "Address 1", class: "col-sm-2 col-xs-12" %>
    <%= m.text_field :address1, class: "col-sm-10 col-xs-12" %>
  </div>

  <div class="form-group">
    <%= m.label "City", class: "col-sm-2 col-xs-12" %>
    <%= m.text_field :city, class: "col-sm-10 col-xs-12" %>
  </div>
  <div class="form-group">
    <%= m.label "Zip", class: "col-sm-2 col-xs-12" %>
    <%= m.text_field :zipcode, class: "col-sm-10 col-xs-12" %>
  </div>

  <div class="form-group">
    <%= m.label "Prescription", class: "col-sm-2 col-xs-12" %>
    <%= m.text_field :prescription_num, class: "col-sm-10 col-xs-12" %>
  </div>

  <div class="form-group">
    <%= m.label "Prescription", class: "col-sm-2 col-xs-12" %>
    <%= m.file_field :prescription_card, class: "col-sm-10 col-xs-12" %>
  </div>
  
  <% if current_user.profile.prescription_card.exists? %>
    <div class="form-group">
      <%= image_tag current_user.profile.prescription_card.url(:normal), class: "col-sm-offset-2 image-responsive"%>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= m.label "Valid Id", class: "col-sm-2 col-xs-12" %>
    <%= m.file_field :idcard, class: "col-sm-10 col-xs-12" %>
  </div>

  <% if current_user.profile.idcard.exists? %>
    <div class="form-group">
      <%= image_tag current_user.profile.idcard.url(:normal), class: "col-sm-offset-2 image-responsive"%>
    </div>
  <% end %>
  
  <div class="col-xs-12 update-btn">
    <%= m.submit 'Create profile', :class => 'btn btn-lg btn-default pull-right', id: 'credit_profile' %>
  </div>

<% end %>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit profile for <%= current_user.email %></h1>

<%= render 'form' %>

app/views/profiles/edit.js.erb
$("#edit_profile").hide().after('<%= j render("form")%>)

app/views/profiles/new.html.erb
<h1>Create Profile for <%= current_user.email %></h1>
<br/>

<%= render 'form' %>

<%= link_to 'Back', user_profile_path %>

app/views/profiles/new.js.erb
$("#new_profile").hide().after('<%= j render("form")%>)

app/views/profiles/show.html.erb
<div id="profile">
  <h1>Logged-in as <%= current_user.email %></h1>

  <% if current_user.profile.nil? %>
  <h2>Please verify your identity</h2>>
  <% else %>
  <div class="col-sm-2">Verified: </div>
  <div class="col-sm-10">
    <%= current_user.profile.verified %><br />
  </div>
  <div class="col-sm-2">Name: </div>
  <div class="col-sm-10"><%= current_user.profile.firstname %> <%= current_user.profile.lastname %><br /></div>
  <div class="col-sm-2">Prescription ID: </div>
  <% if current_user.profile.prescription_card.present?%>
    <div class="profile-img">
      <%= image_tag current_user.profile.prescription_card.url(:normal) %><br />
    </div>
  <% else %>
    None. Please update your profile<br/>
  <% end %><br />
  <div class="col-sm-2">Valid ID Card: </div>
  <% if current_user.profile.idcard.present? %>
    <div class="profile-img">
       <%= image_tag current_user.profile.idcard.url(:normal), class:"image-responsive" %>
    </div>
    <% else %>
      None. Please update your profile<br/>
    <% end %>
  <% end %>

  <div class="col-sm-offset-1">
    <% if current_user.profile.nil? %>
      <%= link_to 'Create Profile', new_user_profile_path(current_user), id: "new_profile", class: "btn btn-default" %>	
    <% else %>
      <%= link_to 'Edit Profile', edit_user_profile_path(current_user), id: "edit_profile", class: "btn btn-default" %>
    <% end %>
  </div>
</div>